name: saypay
description: "SayPay"
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  device_preview:
  animate_do:
  cached_network_image: ^3.4.1
  flutter_secure_storage: ^10.0.0
  another_flushbar: ^1.12.32
  get: ^4.7.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animation/

  fonts:
    - family: Lufga
      fonts:
        - asset: assets/fonts/LufgaLight.ttf
          weight: 300
        - asset: assets/fonts/LufgaRegular.ttf
          weight: 400
        - asset: assets/fonts/LufgaMedium.ttf
          weight: 500
        - asset: assets/fonts/LufgaSemiBold.ttf
          weight: 600
        - asset: assets/fonts/LufgaBold.ttf
          weight: 700
